import './parts/lockscroll.js';
import './parts/mobmenu.js';
// import './parts/navigation.js';
import './parts/modal.js';
// import './parts/scrollto.js';
// import './parts/accordion.js';
// import './parts/tabs.js';
// import './parts/showmore.js';
// import './parts/videoplay.js';
// import './parts/banner.js';
// import './parts/splidecust.js';
// import './parts/splide.js';
// import './parts/sidebar.js';
// import './parts/forms.js';
// import './parts/select.js';
// import './parts/clipboard.js';
